source 'http://rubygems.org'

gem 'thin'
gem 'rake'
gem 'rails', '3.0.10'
gem 'pg'
gem 'haml'
gem 'sass'
gem 'routing-filter'
gem 'json'
gem 'thin'
gem 'em-http-request'
gem 'globalize3', :git => 'https://github.com/svenfuchs/globalize3.git'
