development:
  adapter: postgresql
  database: defuzeme_dev
  username: bigbourin
  min_messages: WARNING

production:
  adapter: postgresql
  database: defuzeme_prod
  username: bigbourin

test:
  adapter: postgresql
  database: defuzeme_test
  username: bigbourin
  min_messages: WARNING

